//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainPrj.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainPrj.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn khi không chọn Khách hàng nào?
        ///Nhấn YES để thoát.
        ///Nhấn NO để chọn lại Khách hàng..
        /// </summary>
        internal static string AreYouSureNotSelectCustomer {
            get {
                return ResourceManager.GetString("AreYouSureNotSelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi truy cập phần tử của mảng.
        /// </summary>
        internal static string ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng ngay.
        /// </summary>
        internal static string CallType1 {
            get {
                return ResourceManager.GetString("CallType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng sau.
        /// </summary>
        internal static string CallType2 {
            get {
                return ResourceManager.GetString("CallType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo trì.
        /// </summary>
        internal static string CallType3 {
            get {
                return ResourceManager.GetString("CallType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gọi đến.
        /// </summary>
        internal static string CardDataStatus1 {
            get {
                return ResourceManager.GetString("CardDataStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gọi đi.
        /// </summary>
        internal static string CardDataStatus2 {
            get {
                return ResourceManager.GetString("CardDataStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý.
        /// </summary>
        internal static string CardDataStatus3 {
            get {
                return ResourceManager.GetString("CardDataStatus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xong.
        /// </summary>
        internal static string CardDataStatus4 {
            get {
                return ResourceManager.GetString("CardDataStatus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhỡ.
        /// </summary>
        internal static string CardDataStatus5 {
            get {
                return ResourceManager.GetString("CardDataStatus5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xong.
        /// </summary>
        internal static string CardDataStatus6 {
            get {
                return ResourceManager.GetString("CardDataStatus6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi decode dữ liệu.
        /// </summary>
        internal static string DecoderError {
            get {
                return ResourceManager.GetString("DecoderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi mã hóa dữ liệu trả về..
        /// </summary>
        internal static string EncodingError {
            get {
                return ResourceManager.GetString("EncodingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra. Nguyên nhân:
        ///.
        /// </summary>
        internal static string ErrorCause {
            get {
                return ResourceManager.GetString("ErrorCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi địa chỉ IP không hợp lệ.
        /// </summary>
        internal static string ErrorIPAddressInvalid {
            get {
                return ResourceManager.GetString("ErrorIPAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of host name is greater than 255 characters.
        /// </summary>
        internal static string ErrorLengthOfHostName {
            get {
                return ResourceManager.GetString("ErrorLengthOfHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng đang được hoàn thiện. Xin vui lòng thử lại sau..
        /// </summary>
        internal static string FunctionProcessing {
            get {
                return ResourceManager.GetString("FunctionProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string Inform {
            get {
                return ResourceManager.GetString("Inform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có kết nối mạng. Xin thử lại..
        /// </summary>
        internal static string InternetConnectionError {
            get {
                return ResourceManager.GetString("InternetConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại mới!.
        /// </summary>
        internal static string NewIncommingPhone {
            get {
                return ResourceManager.GetString("NewIncommingPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket đã bị đóng lại.
        /// </summary>
        internal static string ObjectDisposedException {
            get {
                return ResourceManager.GetString("ObjectDisposedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đủ bộ nhớ.
        /// </summary>
        internal static string OutOfMemory {
            get {
                return ResourceManager.GetString("OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string SearchString {
            get {
                return ResourceManager.GetString("SearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn Khách Hàng.
        /// </summary>
        internal static string SelectorTitleCustomer {
            get {
                return ResourceManager.GetString("SelectorTitleCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn Sale.
        /// </summary>
        internal static string SelectorTitleSale {
            get {
                return ResourceManager.GetString("SelectorTitleSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi truy cập vào Socket.
        /// </summary>
        internal static string SocketException {
            get {
                return ResourceManager.GetString("SocketException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiến trình đang chạy, không thể thay đổi trạng thái!.
        /// </summary>
        internal static string ThreadStateError {
            get {
                return ResourceManager.GetString("ThreadStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối đến cổng:.
        /// </summary>
        internal static string UdpClientArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("UdpClientArgumentOutOfRangeException", resourceCulture);
            }
        }
    }
}
