//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainPrj.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainPrj.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý.
        /// </summary>
        internal static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân tích dữ liệu hoàn thành!.
        /// </summary>
        internal static string AnalyzeTempDataDone {
            get {
                return ResourceManager.GetString("AnalyzeTempDataDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang phân tích dữ liệu!.
        /// </summary>
        internal static string AnalyzingTempData {
            get {
                return ResourceManager.GetString("AnalyzingTempData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/default/callHistorySave.
        /// </summary>
        internal static string API_CALL_HISTORY {
            get {
                return ResourceManager.GetString("API_CALL_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/default/windowOrderCar.
        /// </summary>
        internal static string API_CREATE_CAR_ORDER {
            get {
                return ResourceManager.GetString("API_CREATE_CAR_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://spj.daukhimiennam.com/api/socket/notifyReceived.
        /// </summary>
        internal static string API_NOTIFY_RECEIVED {
            get {
                return ResourceManager.GetString("API_NOTIFY_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/default/windowGetCustomerHistory.
        /// </summary>
        internal static string API_ORDER_HISTORY {
            get {
                return ResourceManager.GetString("API_ORDER_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn khi không chọn Khách hàng nào?
        ///Nhấn YES để thoát.
        ///Nhấn NO để chọn lại Khách hàng..
        /// </summary>
        internal static string AreYouSureNotSelectCustomer {
            get {
                return ResourceManager.GetString("AreYouSureNotSelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn thoát?.
        /// </summary>
        internal static string AreYouSureToClose {
            get {
                return ResourceManager.GetString("AreYouSureToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi truy cập phần tử của mảng.
        /// </summary>
        internal static string ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thế chân.
        /// </summary>
        internal static string Bond {
            get {
                return ResourceManager.GetString("Bond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap call {
            get {
                object obj = ResourceManager.GetObject("call", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.
        /// </summary>
        internal static string CallDateTimeFormat {
            get {
                return ResourceManager.GetString("CallDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng ngay.
        /// </summary>
        internal static string CallType1 {
            get {
                return ResourceManager.GetString("CallType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng sau.
        /// </summary>
        internal static string CallType2 {
            get {
                return ResourceManager.GetString("CallType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo trì.
        /// </summary>
        internal static string CallType3 {
            get {
                return ResourceManager.GetString("CallType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel_order {
            get {
                object obj = ResourceManager.GetObject("cancel_order", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel1 {
            get {
                object obj = ResourceManager.GetObject("cancel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật đơn hàng này!.
        /// </summary>
        internal static string CanNotUpdateOrder {
            get {
                return ResourceManager.GetString("CanNotUpdateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gọi đến.
        /// </summary>
        internal static string CardDataStatus1 {
            get {
                return ResourceManager.GetString("CardDataStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gọi đi.
        /// </summary>
        internal static string CardDataStatus2 {
            get {
                return ResourceManager.GetString("CardDataStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý.
        /// </summary>
        internal static string CardDataStatus3 {
            get {
                return ResourceManager.GetString("CardDataStatus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xong.
        /// </summary>
        internal static string CardDataStatus4 {
            get {
                return ResourceManager.GetString("CardDataStatus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhỡ.
        /// </summary>
        internal static string CardDataStatus5 {
            get {
                return ResourceManager.GetString("CardDataStatus5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xong.
        /// </summary>
        internal static string CardDataStatus6 {
            get {
                return ResourceManager.GetString("CardDataStatus6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - CCS.
        /// </summary>
        internal static string CCSSuffix {
            get {
                return ResourceManager.GetString("CCSSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://android.huongminhgroup.com/coordinatorhelper/autoupdate.xml.
        /// </summary>
        internal static string CheckAutoUpdate {
            get {
                return ResourceManager.GetString("CheckAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EE3224.
        /// </summary>
        internal static string COLOR_BUTTON_NORMAL {
            get {
                return ResourceManager.GetString("COLOR_BUTTON_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 08C012.
        /// </summary>
        internal static string COLOR_BUTTON_SELECTED {
            get {
                return ResourceManager.GetString("COLOR_BUTTON_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap connect {
            get {
                object obj = ResourceManager.GetObject("connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã kết nối với Trung tâm thông báo.
        /// </summary>
        internal static string ConnectedWithNotifyCenter {
            get {
                return ResourceManager.GetString("ConnectedWithNotifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã đóng kết nối tới Trung tâm thông báo.
        /// </summary>
        internal static string ConnectedWithNotifyCenterClosed {
            get {
                return ResourceManager.GetString("ConnectedWithNotifyCenterClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kết nối với Trung tâm thông báo.
        /// </summary>
        internal static string ConnectedWithNotifyCenterError {
            get {
                return ResourceManager.GetString("ConnectedWithNotifyCenterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã nhận dữ liệu từ Trung tâm thông báo.
        /// </summary>
        internal static string ConnectedWithNotifyCenterReceivedData {
            get {
                return ResourceManager.GetString("ConnectedWithNotifyCenterReceivedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối với Trung tâm thông báo đã được mở.
        /// </summary>
        internal static string ConnectionWithNotifyCenterOpened {
            get {
                return ResourceManager.GetString("ConnectionWithNotifyCenterOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có file ghi âm.
        /// </summary>
        internal static string CONTENT00001 {
            get {
                return ResourceManager.GetString("CONTENT00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng đang xử lý.
        /// </summary>
        internal static string CONTENT00002 {
            get {
                return ResourceManager.GetString("CONTENT00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi xảy ra khi convert JSON object.
        /// </summary>
        internal static string ConvertJsonError {
            get {
                return ResourceManager.GetString("ConvertJsonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi tạo Khách Hàng mới!.
        /// </summary>
        internal static string CreateCustomerFailed {
            get {
                return ResourceManager.GetString("CreateCustomerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Khách Hàng mới thành công!.
        /// </summary>
        internal static string CreateCustomerSuccess {
            get {
                return ResourceManager.GetString("CreateCustomerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi xảy ra khi tạo đơn hàng trên web!.
        /// </summary>
        internal static string CreateOrderServerError {
            get {
                return ResourceManager.GetString("CreateOrderServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi xảy ra khi tạo đơn hàng trên web.
        ///Điều phối hãy thoát ra rồi đăng nhập lại!.
        /// </summary>
        internal static string CreateOrderServerError1987 {
            get {
                return ResourceManager.GetString("CreateOrderServerError1987", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo đơn hàng thành công!.
        /// </summary>
        internal static string CreateOrderSuccess {
            get {
                return ResourceManager.GetString("CreateOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo đơn đặt hàng.
        /// </summary>
        internal static string CreateOrderTitle {
            get {
                return ResourceManager.GetString("CreateOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang tạo đơn hàng cho Khách hàng {0} - {3}:
        ///{1}
        ///tại {2}.
        ///Bạn chắn chắn không?.
        /// </summary>
        internal static string CreatingOrder {
            get {
                return ResourceManager.GetString("CreatingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không rõ.
        /// </summary>
        internal static string CustomerNameUnknown {
            get {
                return ResourceManager.GetString("CustomerNameUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vỏ.
        /// </summary>
        internal static string Cylinder {
            get {
                return ResourceManager.GetString("Cylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn lưu thay đổi hay không?.
        /// </summary>
        internal static string DataNotSaveYet {
            get {
                return ResourceManager.GetString("DataNotSaveYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi decode dữ liệu.
        /// </summary>
        internal static string DecoderError {
            get {
                return ResourceManager.GetString("DecoderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd-MM-yyyy.
        /// </summary>
        internal static string DefaultDateTimeFormat {
            get {
                return ResourceManager.GetString("DefaultDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disconnect {
            get {
                object obj = ResourceManager.GetObject("disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap done_black {
            get {
                object obj = ResourceManager.GetObject("done_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap done_small {
            get {
                object obj = ResourceManager.GetObject("done_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không lưu.
        /// </summary>
        internal static string DontSave {
            get {
                return ResourceManager.GetString("DontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_icon {
            get {
                object obj = ResourceManager.GetObject("download_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi mã hóa dữ liệu trả về..
        /// </summary>
        internal static string EncodingError {
            get {
                return ResourceManager.GetString("EncodingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator.Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra. Nguyên nhân:
        ///.
        /// </summary>
        internal static string ErrorCause {
            get {
                return ResourceManager.GetString("ErrorCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi địa chỉ IP không hợp lệ.
        /// </summary>
        internal static string ErrorIPAddressInvalid {
            get {
                return ResourceManager.GetString("ErrorIPAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of host name is greater than 255 characters.
        /// </summary>
        internal static string ErrorLengthOfHostName {
            get {
                return ResourceManager.GetString("ErrorLengthOfHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap finish {
            get {
                object obj = ResourceManager.GetObject("finish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng đang bị tạm khóa. Xin vui lòng thử lại sau..
        /// </summary>
        internal static string FunctionBlocking {
            get {
                return ResourceManager.GetString("FunctionBlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng đang được hoàn thiện. Xin vui lòng thử lại sau..
        /// </summary>
        internal static string FunctionProcessing {
            get {
                return ResourceManager.GetString("FunctionProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap history {
            get {
                object obj = ResourceManager.GetObject("history", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id : {0}.
        /// </summary>
        internal static string IdIs {
            get {
                return ResourceManager.GetString("IdIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có cuộc gọi đến: {0}.
        /// </summary>
        internal static string IncommingCall {
            get {
                return ResourceManager.GetString("IncommingCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string Inform {
            get {
                return ResourceManager.GetString("Inform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận đã đọc được thông báo đơn hàng.
        /// </summary>
        internal static string InformReceivedNotification {
            get {
                return ResourceManager.GetString("InformReceivedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgentId.
        /// </summary>
        internal static string INI_KEY_AGENTID {
            get {
                return ResourceManager.GetString("INI_KEY_AGENTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string INI_KEY_BRAND {
            get {
                return ResourceManager.GetString("INI_KEY_BRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PacketSIP.
        /// </summary>
        internal static string INI_KEY_PACKET_SIP {
            get {
                return ResourceManager.GetString("INI_KEY_PACKET_SIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PacketUDP.
        /// </summary>
        internal static string INI_KEY_PACKET_UDP {
            get {
                return ResourceManager.GetString("INI_KEY_PACKET_UDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string INI_KEY_PASSWORD {
            get {
                return ResourceManager.GetString("INI_KEY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PromoteMoney.
        /// </summary>
        internal static string INI_KEY_PROMOTE_MONEY {
            get {
                return ResourceManager.GetString("INI_KEY_PROMOTE_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpholdPhone.
        /// </summary>
        internal static string INI_KEY_UPHOLD_PHONE {
            get {
                return ResourceManager.GetString("INI_KEY_UPHOLD_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string INI_KEY_USERNAME {
            get {
                return ResourceManager.GetString("INI_KEY_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZiboFilepath.
        /// </summary>
        internal static string INI_KEY_ZIBOSOFT_RECORD_FILEPATH {
            get {
                return ResourceManager.GetString("INI_KEY_ZIBOSOFT_RECORD_FILEPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string INI_SECTION_GENERAL {
            get {
                return ResourceManager.GetString("INI_SECTION_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập giá vỏ:.
        /// </summary>
        internal static string InputCylinderPrice {
            get {
                return ResourceManager.GetString("InputCylinderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tiền trả lại KH:.
        /// </summary>
        internal static string InputCylinderReturn {
            get {
                return ResourceManager.GetString("InputCylinderReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tiền thế chân:.
        /// </summary>
        internal static string InputTheChanValue {
            get {
                return ResourceManager.GetString("InputTheChanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có kết nối mạng. Xin thử lại..
        /// </summary>
        internal static string InternetConnectionError {
            get {
                return ResourceManager.GetString("InternetConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q.
        /// </summary>
        internal static string JSON_ROOT_KEY {
            get {
                return ResourceManager.GetString("JSON_ROOT_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list {
            get {
                object obj = ResourceManager.GetObject("list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách đơn hàng ngày.
        /// </summary>
        internal static string ListOrder {
            get {
                return ResourceManager.GetString("ListOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công!.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logout {
            get {
                object obj = ResourceManager.GetObject("logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon main {
            get {
                object obj = ResourceManager.GetObject("main", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap markedread {
            get {
                object obj = ResourceManager.GetObject("markedread", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap markread {
            get {
                object obj = ResourceManager.GetObject("markread", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có thông tin Khách hàng, cần phải tạo Khách hàng trước!.
        /// </summary>
        internal static string MissCustomerInfor {
            get {
                return ResourceManager.GetString("MissCustomerInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap money_icon_gray {
            get {
                object obj = ResourceManager.GetObject("money_icon_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_Customer {
            get {
                object obj = ResourceManager.GetObject("new_Customer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại mới!.
        /// </summary>
        internal static string NewIncommingPhone {
            get {
                return ResourceManager.GetString("NewIncommingPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Không chọn).
        /// </summary>
        internal static string NoneSelect {
            get {
                return ResourceManager.GetString("NoneSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tồn tại thiết bị nào nhận thông tin SIP packet từ mạng..
        /// </summary>
        internal static string NotDeviceAvailable {
            get {
                return ResourceManager.GetString("NotDeviceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú đã được lưu lại.
        /// </summary>
        internal static string NoteSaved {
            get {
                return ResourceManager.GetString("NoteSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notification {
            get {
                object obj = ResourceManager.GetObject("notification", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notification___Copy {
            get {
                object obj = ResourceManager.GetObject("notification - Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream notifySound1 {
            get {
                return ResourceManager.GetStream("notifySound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream notifySound2 {
            get {
                return ResourceManager.GetStream("notifySound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream notifySound3 {
            get {
                return ResourceManager.GetStream("notifySound3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập giá sản phẩm.
        ///OK: Xác nhận không cần nhập giá.
        ///Cancel: Quay lại nhập giá..
        /// </summary>
        internal static string NotInputProductPrice {
            get {
                return ResourceManager.GetString("NotInputProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa đăng nhập..
        /// </summary>
        internal static string NotLoginYet {
            get {
                return ResourceManager.GetString("NotLoginYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có thông tin khách hàng..
        /// </summary>
        internal static string NotSelectCustomer {
            get {
                return ResourceManager.GetString("NotSelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn NV giao nhận hoặc NV CCS..
        /// </summary>
        internal static string NotSelectDeliverCCS {
            get {
                return ResourceManager.GetString("NotSelectDeliverCCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn loại gas nào!.
        /// </summary>
        internal static string NotSelectMaterial {
            get {
                return ResourceManager.GetString("NotSelectMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn sản phẩm nào..
        /// </summary>
        internal static string NotSelectProducts {
            get {
                return ResourceManager.GetString("NotSelectProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket đã bị đóng lại.
        /// </summary>
        internal static string ObjectDisposedException {
            get {
                return ResourceManager.GetString("ObjectDisposedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ordernow {
            get {
                object obj = ResourceManager.GetObject("ordernow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ordertruck {
            get {
                object obj = ResourceManager.GetObject("ordertruck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đủ bộ nhớ.
        /// </summary>
        internal static string OutOfMemory {
            get {
                return ResourceManager.GetString("OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap phone {
            get {
                object obj = ResourceManager.GetObject("phone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap record {
            get {
                object obj = ResourceManager.GetObject("record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyyMMdd.
        /// </summary>
        internal static string RecordDateTimeFormat {
            get {
                return ResourceManager.GetString("RecordDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap report {
            get {
                object obj = ResourceManager.GetObject("report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin Đại Lý thành công!.
        /// </summary>
        internal static string RequestAgentInfoSuccess {
            get {
                return ResourceManager.GetString("RequestAgentInfoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang gửi yêu cầu thông tin Đại Lý....
        /// </summary>
        internal static string RequestingAgentInformation {
            get {
                return ResourceManager.GetString("RequestingAgentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang gửi yêu cầu tạo mới Khách hàng....
        /// </summary>
        internal static string RequestingCreateCustomer {
            get {
                return ResourceManager.GetString("RequestingCreateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang gửi yêu cầu tạo Đơn hàng....
        /// </summary>
        internal static string RequestingCreateOrder {
            get {
                return ResourceManager.GetString("RequestingCreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang gửi yêu cầu đăng nhập....
        /// </summary>
        internal static string RequestingLogin {
            get {
                return ResourceManager.GetString("RequestingLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang gửi yêu cầu đăng xuất....
        /// </summary>
        internal static string RequestingLogout {
            get {
                return ResourceManager.GetString("RequestingLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang gửi yêu cầu lịch sử giao dịch....
        /// </summary>
        internal static string RequestingOrderHistory {
            get {
                return ResourceManager.GetString("RequestingOrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang gửi yêu cầu cập nhật data....
        /// </summary>
        internal static string RequestingTempData {
            get {
                return ResourceManager.GetString("RequestingTempData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất thành công!.
        /// </summary>
        internal static string RequestLogoutSuccess {
            get {
                return ResourceManager.GetString("RequestLogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật lịch sử giao dịch thành công!.
        /// </summary>
        internal static string RequestOrderHistorySuccess {
            get {
                return ResourceManager.GetString("RequestOrderHistorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật data hoàn thành!.
        /// </summary>
        internal static string RequestTempDataSuccess {
            get {
                return ResourceManager.GetString("RequestTempDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang gửi yêu cầu cập nhật thông tin Đại lý....
        /// </summary>
        internal static string RequestUpdateAgentCellPhone {
            get {
                return ResourceManager.GetString("RequestUpdateAgentCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string RESPONSE_STATUS_FAILED {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string RESPONSE_STATUS_SUCCESS {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý đang sử dụng card ghi âm cũ. Cần phải khởi động lại chương trình thì hệ thống mới nhảy Line khi có cuộc gọi đến được. Sau khi nhấn OK để tắt thông báo này, khởi động lại chương trình!.
        /// </summary>
        internal static string RestartProgram {
            get {
                return ResourceManager.GetString("RestartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string SearchString {
            get {
                return ResourceManager.GetString("SearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn sản phẩm.
        /// </summary>
        internal static string SelectItems {
            get {
                return ResourceManager.GetString("SelectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn Đại lý.
        /// </summary>
        internal static string SelectorTitleAgent {
            get {
                return ResourceManager.GetString("SelectorTitleAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn Khách Hàng.
        /// </summary>
        internal static string SelectorTitleCustomer {
            get {
                return ResourceManager.GetString("SelectorTitleCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn vỏ.
        /// </summary>
        internal static string SelectorTitleCylinder {
            get {
                return ResourceManager.GetString("SelectorTitleCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn Sale.
        /// </summary>
        internal static string SelectorTitleSale {
            get {
                return ResourceManager.GetString("SelectorTitleSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn hàng khuyến mãi.
        /// </summary>
        internal static string SelectPromotes {
            get {
                return ResourceManager.GetString("SelectPromotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi truy cập vào Socket.
        /// </summary>
        internal static string SocketException {
            get {
                return ResourceManager.GetString("SocketException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        internal static string SPLITER_SPACE_STR {
            get {
                return ResourceManager.GetString("SPLITER_SPACE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string SPLITER_STR {
            get {
                return ResourceManager.GetString("SPLITER_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiến trình đang chạy, không thể thay đổi trạng thái!.
        /// </summary>
        internal static string ThreadStateError {
            get {
                return ResourceManager.GetString("ThreadStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap timer {
            get {
                object obj = ResourceManager.GetObject("timer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transfer {
            get {
                object obj = ResourceManager.GetObject("transfer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối đến cổng:.
        /// </summary>
        internal static string UdpClientArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("UdpClientArgumentOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ!.
        /// </summary>
        internal static string UpdateAgentCellPhoneError {
            get {
                return ResourceManager.GetString("UpdateAgentCellPhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật đơn hàng thành công!.
        /// </summary>
        internal static string UpdateOrderSuccess {
            get {
                return ResourceManager.GetString("UpdateOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật đơn hàng.
        /// </summary>
        internal static string UpdateOrderTitle {
            get {
                return ResourceManager.GetString("UpdateOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uphold {
            get {
                object obj = ResourceManager.GetObject("uphold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0838 408 408.
        /// </summary>
        internal static string UPHOLD_PHONE_HCM {
            get {
                return ResourceManager.GetString("UPHOLD_PHONE_HCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upload_tray {
            get {
                object obj = ResourceManager.GetObject("upload_tray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warehouse {
            get {
                object obj = ResourceManager.GetObject("warehouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt buộc phải chọn Đại lý.
        /// </summary>
        internal static string YouMustSelectAnAgent {
            get {
                return ResourceManager.GetString("YouMustSelectAnAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\VOC.
        /// </summary>
        internal static string ZIBOSOFT_RECORD_FILEPATH_DEFAULT {
            get {
                return ResourceManager.GetString("ZIBOSOFT_RECORD_FILEPATH_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1972.
        /// </summary>
        internal static string ZiboUdpPort {
            get {
                return ResourceManager.GetString("ZiboUdpPort", resourceCulture);
            }
        }
    }
}
