//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainPrj.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainPrj.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý.
        /// </summary>
        internal static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân tích dữ liệu hoàn thành!.
        /// </summary>
        internal static string AnalyzeTempDataDone {
            get {
                return ResourceManager.GetString("AnalyzeTempDataDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang phân tích dữ liệu!.
        /// </summary>
        internal static string AnalyzingTempData {
            get {
                return ResourceManager.GetString("AnalyzingTempData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn khi không chọn Khách hàng nào?
        ///Nhấn YES để thoát.
        ///Nhấn NO để chọn lại Khách hàng..
        /// </summary>
        internal static string AreYouSureNotSelectCustomer {
            get {
                return ResourceManager.GetString("AreYouSureNotSelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn thoát?.
        /// </summary>
        internal static string AreYouSureToClose {
            get {
                return ResourceManager.GetString("AreYouSureToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi truy cập phần tử của mảng.
        /// </summary>
        internal static string ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng ngay.
        /// </summary>
        internal static string CallType1 {
            get {
                return ResourceManager.GetString("CallType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng sau.
        /// </summary>
        internal static string CallType2 {
            get {
                return ResourceManager.GetString("CallType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo trì.
        /// </summary>
        internal static string CallType3 {
            get {
                return ResourceManager.GetString("CallType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel_order {
            get {
                object obj = ResourceManager.GetObject("cancel_order", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel1 {
            get {
                object obj = ResourceManager.GetObject("cancel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gọi đến.
        /// </summary>
        internal static string CardDataStatus1 {
            get {
                return ResourceManager.GetString("CardDataStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gọi đi.
        /// </summary>
        internal static string CardDataStatus2 {
            get {
                return ResourceManager.GetString("CardDataStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý.
        /// </summary>
        internal static string CardDataStatus3 {
            get {
                return ResourceManager.GetString("CardDataStatus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xong.
        /// </summary>
        internal static string CardDataStatus4 {
            get {
                return ResourceManager.GetString("CardDataStatus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhỡ.
        /// </summary>
        internal static string CardDataStatus5 {
            get {
                return ResourceManager.GetString("CardDataStatus5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xong.
        /// </summary>
        internal static string CardDataStatus6 {
            get {
                return ResourceManager.GetString("CardDataStatus6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://android.huongminhgroup.com/coordinatorhelper/autoupdate.xml.
        /// </summary>
        internal static string CheckAutoUpdate {
            get {
                return ResourceManager.GetString("CheckAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi tạo Khách Hàng mới!.
        /// </summary>
        internal static string CreateCustomerFailed {
            get {
                return ResourceManager.GetString("CreateCustomerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Khách Hàng mới thành công!.
        /// </summary>
        internal static string CreateCustomerSuccess {
            get {
                return ResourceManager.GetString("CreateCustomerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi xảy ra khi tạo đơn hàng trên web!.
        /// </summary>
        internal static string CreateOrderServerError {
            get {
                return ResourceManager.GetString("CreateOrderServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo đơn hàng thành công!.
        /// </summary>
        internal static string CreateOrderSuccess {
            get {
                return ResourceManager.GetString("CreateOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn lưu thay đổi hay không?.
        /// </summary>
        internal static string DataNotSaveYet {
            get {
                return ResourceManager.GetString("DataNotSaveYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi decode dữ liệu.
        /// </summary>
        internal static string DecoderError {
            get {
                return ResourceManager.GetString("DecoderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap done_black {
            get {
                object obj = ResourceManager.GetObject("done_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap done_small {
            get {
                object obj = ResourceManager.GetObject("done_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không lưu.
        /// </summary>
        internal static string DontSave {
            get {
                return ResourceManager.GetString("DontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_icon {
            get {
                object obj = ResourceManager.GetObject("download_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi mã hóa dữ liệu trả về..
        /// </summary>
        internal static string EncodingError {
            get {
                return ResourceManager.GetString("EncodingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator.Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra. Nguyên nhân:
        ///.
        /// </summary>
        internal static string ErrorCause {
            get {
                return ResourceManager.GetString("ErrorCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi địa chỉ IP không hợp lệ.
        /// </summary>
        internal static string ErrorIPAddressInvalid {
            get {
                return ResourceManager.GetString("ErrorIPAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of host name is greater than 255 characters.
        /// </summary>
        internal static string ErrorLengthOfHostName {
            get {
                return ResourceManager.GetString("ErrorLengthOfHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap finish {
            get {
                object obj = ResourceManager.GetObject("finish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng đang được hoàn thiện. Xin vui lòng thử lại sau..
        /// </summary>
        internal static string FunctionProcessing {
            get {
                return ResourceManager.GetString("FunctionProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap history {
            get {
                object obj = ResourceManager.GetObject("history", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id : {0}.
        /// </summary>
        internal static string IdIs {
            get {
                return ResourceManager.GetString("IdIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có cuộc gọi đến: {0}.
        /// </summary>
        internal static string IncommingCall {
            get {
                return ResourceManager.GetString("IncommingCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string Inform {
            get {
                return ResourceManager.GetString("Inform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có kết nối mạng. Xin thử lại..
        /// </summary>
        internal static string InternetConnectionError {
            get {
                return ResourceManager.GetString("InternetConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list {
            get {
                object obj = ResourceManager.GetObject("list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách đơn hàng ngày.
        /// </summary>
        internal static string ListOrder {
            get {
                return ResourceManager.GetString("ListOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công!.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon main {
            get {
                object obj = ResourceManager.GetObject("main", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có thông tin Khách hàng, cần phải tạo Khách hàng trước!.
        /// </summary>
        internal static string MissCustomerInfor {
            get {
                return ResourceManager.GetString("MissCustomerInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap money_icon_gray {
            get {
                object obj = ResourceManager.GetObject("money_icon_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_Customer {
            get {
                object obj = ResourceManager.GetObject("new_Customer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại mới!.
        /// </summary>
        internal static string NewIncommingPhone {
            get {
                return ResourceManager.GetString("NewIncommingPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Không chọn).
        /// </summary>
        internal static string NoneSelect {
            get {
                return ResourceManager.GetString("NoneSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú đã được lưu lại.
        /// </summary>
        internal static string NoteSaved {
            get {
                return ResourceManager.GetString("NoteSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa đăng nhập..
        /// </summary>
        internal static string NotLoginYet {
            get {
                return ResourceManager.GetString("NotLoginYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có thông tin khách hàng..
        /// </summary>
        internal static string NotSelectCustomer {
            get {
                return ResourceManager.GetString("NotSelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn NV giao nhận hoặc NV CCS..
        /// </summary>
        internal static string NotSelectDeliverCCS {
            get {
                return ResourceManager.GetString("NotSelectDeliverCCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn sản phẩm nào..
        /// </summary>
        internal static string NotSelectProducts {
            get {
                return ResourceManager.GetString("NotSelectProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket đã bị đóng lại.
        /// </summary>
        internal static string ObjectDisposedException {
            get {
                return ResourceManager.GetString("ObjectDisposedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ordernow {
            get {
                object obj = ResourceManager.GetObject("ordernow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ordertruck {
            get {
                object obj = ResourceManager.GetObject("ordertruck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đủ bộ nhớ.
        /// </summary>
        internal static string OutOfMemory {
            get {
                return ResourceManager.GetString("OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap report {
            get {
                object obj = ResourceManager.GetObject("report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin Đại Lý thành công!.
        /// </summary>
        internal static string RequestAgentInfoSuccess {
            get {
                return ResourceManager.GetString("RequestAgentInfoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang gửi yêu cầu thông tin Đại Lý....
        /// </summary>
        internal static string RequestingAgentInformation {
            get {
                return ResourceManager.GetString("RequestingAgentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang gửi yêu cầu tạo mới Khách hàng....
        /// </summary>
        internal static string RequestingCreateCustomer {
            get {
                return ResourceManager.GetString("RequestingCreateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang gửi yêu cầu đăng nhập....
        /// </summary>
        internal static string RequestingLogin {
            get {
                return ResourceManager.GetString("RequestingLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang gửi yêu cầu cập nhật data....
        /// </summary>
        internal static string RequestingTempData {
            get {
                return ResourceManager.GetString("RequestingTempData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật data hoàn thành!.
        /// </summary>
        internal static string RequestTempDataSuccess {
            get {
                return ResourceManager.GetString("RequestTempDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string SearchString {
            get {
                return ResourceManager.GetString("SearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn sản phẩm.
        /// </summary>
        internal static string SelectItems {
            get {
                return ResourceManager.GetString("SelectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn Đại lý.
        /// </summary>
        internal static string SelectorTitleAgent {
            get {
                return ResourceManager.GetString("SelectorTitleAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn Khách Hàng.
        /// </summary>
        internal static string SelectorTitleCustomer {
            get {
                return ResourceManager.GetString("SelectorTitleCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn vỏ.
        /// </summary>
        internal static string SelectorTitleCylinder {
            get {
                return ResourceManager.GetString("SelectorTitleCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn Sale.
        /// </summary>
        internal static string SelectorTitleSale {
            get {
                return ResourceManager.GetString("SelectorTitleSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn hàng khuyến mãi.
        /// </summary>
        internal static string SelectPromotes {
            get {
                return ResourceManager.GetString("SelectPromotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi truy cập vào Socket.
        /// </summary>
        internal static string SocketException {
            get {
                return ResourceManager.GetString("SocketException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiến trình đang chạy, không thể thay đổi trạng thái!.
        /// </summary>
        internal static string ThreadStateError {
            get {
                return ResourceManager.GetString("ThreadStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transfer {
            get {
                object obj = ResourceManager.GetObject("transfer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối đến cổng:.
        /// </summary>
        internal static string UdpClientArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("UdpClientArgumentOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật đơn hàng thành công!.
        /// </summary>
        internal static string UpdateOrderSuccess {
            get {
                return ResourceManager.GetString("UpdateOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upload_tray {
            get {
                object obj = ResourceManager.GetObject("upload_tray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warehouse {
            get {
                object obj = ResourceManager.GetObject("warehouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt buộc phải chọn Đại lý.
        /// </summary>
        internal static string YouMustSelectAnAgent {
            get {
                return ResourceManager.GetString("YouMustSelectAnAgent", resourceCulture);
            }
        }
    }
}
